import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Header } from '../components/header';
import { Hero } from '../components/hero';
import { Main } from '../components/main';
import { Footer } from '../components/footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head'
import Script from 'next/script';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
     <Head>
        <title>Konnectify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script src='/static/main.js'/>
      </Head>
    <div className="main">
      <Header/>
      <Hero/>
      <Main/>
      <Footer/>
    </div>
    </>
  )
}